name: GLaDOS-auto

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */1 * * *

jobs:
  GLaDOS-auto:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: checkin
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          ./checkin.sh
